<?php
namespace AppBundle\Repository;


/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends \Doctrine\ORM\EntityRepository
{
    public function sortMusic ($array)
    {
        if(isset($array['orderBy']))
        {
            switch($array['orderBy'])
            {
                case "name": return $orderBy='song.name'; break;
                case "singer": return $orderBy='song.singer'; break;
                case "album": return $orderBy='song.album'; break;
                case "year": return $orderBy='song.year'; break;
                case "genre": return $orderBy='song.genre'; break;
                default: return $orderBy='song.id';
            }
        }
        else
        {
            return $orderBy='song.id';
        }
    }

    public function getId ($array)
    {
        if(isset($array['next']))
        {
            $id=$array['song_id'];
            if(isset($array['songs_ended']))
                $id;
            else
                $id+=20;
        }
        else
            if(isset($array['previous']))
            {
                $id=$array['song_id'];
                $id-=20;
            }
            else
                if(isset($array['song_id']))
                {
                    $id=$array['song_id'];
                }
                else
                    $id=1;
        if($id<1)
        {
            $id=1;
            return $id;
        }
        else
            {
                return $id;
            }
    }
}
